version: '3'
services:
    social-nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./social-net:/app
        depends_on:
            - social-php-fpm
        ports:
            - "8333:80"
    social-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - social-postgres
            - social-redis
            - social-queue-redis
    social-php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - social-postgres
            - social-redis
            - social-queue-redis
    social-postgres:
        image: postgres:11.2-alpine
        volumes:
            - social-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54327:5432"
    social-redis:
        image: redis:5.0-alpine
        volumes:
            - social-redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'
    social-queue-redis:
        image: redis:5.0-alpine
        volumes:
            - social-queue-redis:/data

volumes:
    social-postgres:
    social-redis:
    social-queue-redis:
    composer:
